### ISSUE TITLE
Incorrect metadata registered with maven repo

### ISSUE THREAD

**Issue by lbenedetto** [eclipse-ee4j/beanvalidation-api#178]
While writing a tool to check for updates to my dependencies, I noticed that the central maven repository has incorrect information about this package.

The information seen here is correct, with multiple versions available.
https://repo1.maven.org/maven2/jakarta/validation/jakarta.validation-api/

However, the actual file that most automatic tools would be parsing says that 2.0.1 is the ONLY version. It looks like the file has not been updated since the initial release in 2018

https://repo1.maven.org/maven2/jakarta/validation/jakarta.validation-api/maven-metadata.xml

```
<metadata>
  <groupId>jakarta.validation</groupId>
  <artifactId>jakarta.validation-api</artifactId>
  <versioning>
    <latest>2.0.1</latest>
    <release>2.0.1</release>
    <versions>
      <version>2.0.1</version>
    </versions>
    <lastUpdated>20181126155025</lastUpdated>
  </versioning>
</metadata>
```

**Comment by pzygielo** [comment]
This project does not maintain Maven Central. Report to https://issues.sonatype.org/ instead.

**Comment by lbenedetto** [comment]
It is my understanding that updating the maven-metadata.xml file is the responsibility of the client doing the deploy.
It seems spring security had a similar issue and resolving it required them to change something on their end, and then ask sonatype to trigger a regeneration of the metadata files.
 https://issues.sonatype.org/browse/MVNCENTRAL-6820

**Comment by starksm64** [comment]
The maven-metadata.xml file is part of the maven repository infrastructure, and we have no control over that. The referenced issue seems to indicate there was concern that a particular mirror host was being used to publish artifacts to, but the eclipse ci release jobs don't do that, and in the end the issue was problems with sync jobs on the maven central infrastructure side.

I have created a sonatype issue:
https://issues.sonatype.org/browse/MVNCENTRAL-7435

**Comment by lbenedetto** [comment]
The issue has been resolved
